name: action-runner

services:
  runner:
    deploy:
      replicas: 3
    build:
      context: .
      args:
        RUNNER_VERSION: ${RUNNER_VERSION:-2.328.0}
        DOTNET_CHANNEL: ${DOTNET_CHANNEL:-10.0}
        GO_VERSION: ${GO_VERSION:-1.26.5}
        NODE_VERSION: ${NODE_VERSION:-26.5.1}
    environment:
      GITHUB_TOKEN:
      RUNNER_NAME:
      RUNNER_LABELS: ${RUNNER_LABELS:-ubuntu-24.04}
    volumes:
      - /runner/_work
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
