name: action-runner

services:
  runner:
    image: ghcr.io/cntryl/build:${IMAGE_TAG:-latest}
    deploy:
      replicas: 2
    environment:
      GITHUB_TOKEN:
      RUNNER_NAME:
      RUNNER_LABELS: ${RUNNER_LABELS:-ubuntu-24.04}
    volumes:
      - /runner/_work
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
